### ISSUE TITLE
Injector Reference issue

### ISSUE THREAD

**Issue by bobrot** [robotlegs-sharp/robotlegs-sharp-framework#10]
Hi, I've pulled latest from both robotlegs-sharp and swiftsuspenders-sharp and attached them to my project. When I attempt to map a model object with code in your examples:

`injector.Map<IApplicationModel>().ToSingleton<ApplicationModel>();`

I get this error:

Error	CS7069	Reference to type 'InjectionMapping' claims it is defined in 'swiftsuspenders-sharp', but it could not be found

I've recompiled latest of swift suspenders myself (as the dll on github is only the debug version), but nothing has changed.

**Comment by prankard** [comment]
Hi Bobrot,
Thanks for trying Robotlegs Sharp.
I've re-compiled the swiftsupsenders-sharp as a release build. Currently you can find the file [here](https://drive.google.com/file/d/0Bz_SvC94SB9DY3htV2E5TTYxXzg/view?usp=sharing).

I'll amend it to the repo today.
I've tested it by replacing the swiftsuspenders-sharp dll on the [hello world project](https://github.com/robotlegs-sharp/unity-hello-world) with the release build and it runs.

Please let me know if this release dll works for you.
