### ISSUE TITLE
Can add MacroCommand like PureMVC do?

### ISSUE THREAD

**Issue by cosmos53076** [robotlegs-sharp/robotlegs-sharp-framework#11]
just like this:
[https://github.com/PureMVC/puremvc-csharp-standard-framework/blob/master/PureMVC/Patterns/Command/MacroCommand.cs](url)

**Comment by prankard** [comment]
Hey,
There is already a way of executing lots of commands in Robotlegs. If you need to check out the [DirectCommandMap](https://github.com/robotlegs-sharp/robotlegs-sharp-framework/tree/master/src/Robotlegs/Bender/Extensions/DirectCommand), you could wrap it up into a MacroCommand if you wish, however this should be fine.

```csharp
using Robotlegs.Bender.Extensions.CommandCenter.API;
using Robotlegs.Bender.Extensions.DirectCommand.API;

namespace helloworld.controller.commands
{
    public class DirectCommandMapExampleCommand : ICommand
    {
        [Inject]
        public IDirectCommandMap directCommandMap;

        public void Execute()
        {
            directCommandMap.Map<DoThisFirstCommand>()
                            .Map<DoThisNextCommand>()
                            .Map<DontForgetThisOneTooCommand>()
                            .Map<FinallyDoThisCommand>()
                            .Execute();
        }
    }
}
```

**Comment by cosmos53076** [comment]
Ok, thanks
