### ISSUE TITLE
Link loss

### ISSUE THREAD

**Issue by NeverMore-Father** [robotlegs-sharp/robotlegs-sharp-framework#16]
https://github.com/robotlegs-sharp/robotlegs-sharp-framework/blob/master/docs/TheInternals.md

It's a great framework, and I want to get to know him better.

Many of the links in this article failed when I tried to learn how it worked

**Comment by prankard** [comment]
Thanks for finding this bug.
We've updated all the hyperlinks on that page (we changed all the namespace from camelCase to PascalCase to confirm with C# which broke all those links)
