### ISSUE TITLE
Rename ILogger

### ISSUE THREAD

**Issue by mattmurton** [robotlegs-sharp/robotlegs-sharp-framework#6]
Unity have now added their own ILogger Class (UnityEngine.ILogger).

This has introduced some rather annoying ambiguous reference errors when using Robotlegs ILogger without prefixing the namespace.
It's annoying to always need to do that so I suggest we rename the ILogger interface, maybe IRobotlegsLogger?

It's a bit longer but at least it should always be unique.

What do you think @prankard ?

**Comment by mikecann** [comment]
Gets my vote :+1:

**Comment by prankard** [comment]
Hmm, my gut to is keep this framework as close to the original RL framework as possible, So renaming classes is not a great idea.

However, if you use the ILogger, this is _really_ annoying. And one of the best things about RL was that it does a _LOT_ for you, and by conflicting with other classes actually takes away the simplicity of using the framework.

At first glance I wanted to inject the ILogger Unity class which we would map as the logger. However, it's more like an ILogTarget not an ILogger (the classes are very different).

So, let's change the name. Keeping it small as possible for me is best. IRobotlegsLogger is pretty annoying to type out constantly. But might be an option. My ideas for a classname are as follows:

ITracer
IReport
IDebug
ILog
IRogotlegsLogger
IContextLogger
ILogManagerLogger

I'm thinking **ITracer**, as an homage to it's old platform.

And if we do that, we should then rename the other classes:
TraceManager
ITraceTarget
ITracer

That should clear up the imports.

Here is how the Log classes work:
* LogManager - Passes logs to multiple log targets, also can make ILoggers to log to all it's targets
* ILogger - What you inject to log messages, it also tracks who logged this. This is grabbed from the LogManager
* ILogTarget - Who logs all the messages to Console (or to any other view)

**Comment by mikecann** [comment]
Sounds good @prankard :)

**Comment by prankard** [comment]
Due to a much larger change that what I had intended, I decided to rename this to **ILogging** instead.
Otherwise, all the framework methods and enums change like so:
```
traceTarget.Trace();
traceManager.GetTracer();
context.TraceLevel = TraceLevel.Debug;
```
Even thought it makes sense, it's very different from the original, and I want to keep it familiar with those who used the original framework.

So future use of logger:
```
class TestCommand
{
	[Inject] public ILogging logger;
	
	public void Execute()
	{
		logger.Warn("The logger injection rule has changed from ILogger to ILogging, please be aware");
	}
}
```
