### ISSUE TITLE
Namespace to follow c# standards

### ISSUE THREAD

**Issue by prankard** [robotlegs-sharp/robotlegs-sharp-framework#7]
We are going to be doing a very large change to the framework. To make the namespaces to Pascal casing as per the documentation on Microsoft's standards:
https://msdn.microsoft.com/library/ms229043%28v=vs.100%29.aspx

From:
**robotlegs.bender.framework.api
robotlegs.bender.framework.impl
robotlegs.bender.extensions.commandCenter.dsl
robotlegs.bender.extensions.enhancedLogging**

To:
**Robotlegs.Bender.Framework.API
Robotlegs.Bender.Framework.Impl
Robotlegs.Bender.Extensions.CommandCenter.DSL
Robotlegs.Bender.Extensions.EnhancedLogging**

We feel that it should be this in the future, and the sooner we do it with less users, the easier it will be for the change. It should in the next update of Robotlegs shortly.

**Comment by mikecann** [comment]
Okay, thanks for the heads up.

**Comment by prankard** [comment]
Updated namespaces and example projects
